spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/coupon_example
    username: root
    password : 3419
